### ISSUE TITLE
Custom Dataset error

### ISSUE THREAD

**Issue by Sidd1609** [orrzohar/PROB#25]

**Comment by Sidd1609** [comment]
@orrzohar 
Having the issue I believe with loading images, 


Traceback (most recent call last):
  File "/DATA/siddharth/PROB/main_open_world.py", line 482, in <module>
    main(args)
  File "/DATA/siddharth/PROB/main_open_world.py", line 336, in main
    train_stats = train_one_epoch(
  File "/DATA/siddharth/PROB/engine.py", line 92, in train_one_epoch
    samples, targets = prefetcher.next()
  File "/DATA/siddharth/PROB/datasets/data_prefetcher.py", line 62, in next
    self.preload()
  File "/DATA/siddharth/PROB/datasets/data_prefetcher.py", line 25, in preload
    self.next_samples, self.next_targets = next(self.loader)
  File "/DATA/siddharth/anaconda3/envs/PROB/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/DATA/siddharth/anaconda3/envs/PROB/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/DATA/siddharth/anaconda3/envs/PROB/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/DATA/siddharth/anaconda3/envs/PROB/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/DATA/siddharth/anaconda3/envs/PROB/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/DATA/siddharth/anaconda3/envs/PROB/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/DATA/siddharth/anaconda3/envs/PROB/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/DATA/siddharth/PROB/datasets/torchvision_datasets/open_world.py", line 333, in __getitem__
    img, target = self.transforms[-1](img, target)
  File "/DATA/siddharth/PROB/datasets/transforms.py", line 274, in __call__
    image, target = t(image, target)
  File "/DATA/siddharth/PROB/datasets/transforms.py", line 194, in __call__
    return hflip(img, target)
  File "/DATA/siddharth/PROB/datasets/transforms.py", line 74, in hflip
    boxes = boxes[:, [2, 1, 0, 3]] * torch.as_tensor([-1, 1, -1, 1]) + torch.as_tensor([w, 0, w, 0])
IndexError: too many indices for tensor of dimension 1
